name: Actions Makepkg - Package database
description: Takes packages and creates a new database.

branding:
  icon: database
  color: green

inputs:
  dir:
    description: >-
      Absolute path to directory containing packages.
    required: true
  reponame:
    description: >-
      Name of repository to create.
    required: true

runs:
  using: docker
  image: dockerfile
  args:
    - ${{ inputs.dir }}
    - ${{ inputs.reponame }}