name: Actions Makepkg
description: Builds a PKGBUILD

branding:
  icon: package
  color: green

inputs:
  dir:
    description: >-
      Absolute path to PKGBUILD directory.
    required: true
  command:
    description: >-
      Command to run before building.
    required: false
  pgpkey:
    description: >-
      PGP key to use for signing the package.
      Should be a base64 encoded string.
    required: false
  march:
    description: >-
      Architecture to build for.
      Defaults to "x86-64".
    required: false
    default: 'x86-64'
  mtune:
    description: >-
      Tunes the build for a specific CPU.
      Defaults to "generic".
    required: false
    default: 'generic'
  skipruntimedeps:
    description: >-
      Boolean that specifies if the script should install runtime dependencies or not.
      Might result in a faster build since less packages are downloaded but might not build at all.
    required: false
    default: false

runs:
  using: docker
  image: docker://ghcr.io/spacefall/actions-makepkg:main
  args:
    - ${{ inputs.dir }}
    - ${{ inputs.command }}
    - ${{ inputs.pgpkey }}
    - ${{ inputs.march }}
    - ${{ inputs.mtune }}
    - ${{ inputs.skipruntimedeps }}
