concurrency:
  group: build-docker
  cancel-in-progress: true
  
on:
  schedule:
    - cron: "0 14 * * 1,3,5"
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: btmc/github-action-docker-build@main
