concurrency:
  group: build-docker
  cancel-in-progress: true
  
on:
  schedule:
    - cron: "0 0 * * 0"
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: btmc/github-action-docker-build@main
